### ISSUE TITLE
 PASCAL-Person-Part-dataset

### ISSUE THREAD

**Issue by wojiaoyanmin** [kevinlin311tw/CDCL-human-part-segmentation#11]
hi 
Thanks for your sharing
Where can I get the  PASCAL-Person-Part dataset please?

**Comment by ZHUXUHAN** [comment]
oh, i also want to get the PASCAL-Person-Part! thanks for your sharing.

**Comment by kevinlin311tw** [comment]
Please download it via the following website: http://liangchiehchen.com/projects/DeepLab.html
